/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface Device {
  id: number;
  type: string;
}

export interface Visit {
  city: string | null;
  country: string | null;
  countryCode: string | null;
  createdAt: Generated<Timestamp>;
  deviceId: number | null;
  endAt: Generated<Timestamp>;
  id: Generated<number>;
  ip: string;
  lat: number | null;
  lon: number | null;
  referrer: string | null;
  region: string | null;
  regionName: string | null;
  userAgent: string | null;
  visiterId: string;
}

export interface Visiter {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  Device: Device;
  Visit: Visit;
  Visiter: Visiter;
}
