version: "3.9"

services:
  db:
    image: postgres
    container_name: portfolio-db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT

volumes:
  postgres:
    name: postgres_data
